let
    Source = Excel.Workbook(File.Contents("C:\Users\nagal\Downloads\EmployeeData.xlsx"), null, true),
    EmployeeData1_Sheet = Source{[Item="EmployeeData1",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(EmployeeData1_Sheet, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"EmployeeID", Int64.Type}, {"NationalIDNumber", Int64.Type}, {"ContactID", Int64.Type}, {"LoginID", type text}, {"ManagerID", Int64.Type}, {"Title", type text}, {"BirthDate", type datetime}, {"MaritalStatus", type text}, {"Gender", type text}, {"HireDate", type datetime}, {"Dept", type text}, {"Salary", Int64.Type}, {"Job Grade", type text}, {"CurrentFlag", Int64.Type}, {"rowguid", type text}}),
    #"Removed Column National ID" = Table.RemoveColumns(#"Changed Type",{"NationalIDNumber"}),
    #"Change Title to FullName" = Table.RenameColumns(#"Removed Column National ID",{{"Title", "Full Name"}}),
    #"BirthDate Date Time to Date" = Table.TransformColumnTypes(#"Change Title to FullName",{{"BirthDate", type date}}),
    #"Replace S to Single" = Table.ReplaceValue(#"BirthDate Date Time to Date","S","Single",Replacer.ReplaceText,{"MaritalStatus"}),
    #"Replace M to Married" = Table.ReplaceValue(#"Replace S to Single","M","Married",Replacer.ReplaceText,{"MaritalStatus"}),
    #"Replace M to Male" = Table.ReplaceValue(#"Replace M to Married","M","Male",Replacer.ReplaceText,{"Gender"}),
    #"Replace F to Female" = Table.ReplaceValue(#"Replace M to Male","F","Female",Replacer.ReplaceText,{"Gender"}),
    #"HireDate DateTime to Date" = Table.TransformColumnTypes(#"Replace F to Female",{{"HireDate", type date}}),
    #"Removed CurrentFlag,Rowguid" = Table.RemoveColumns(#"HireDate DateTime to Date",{"CurrentFlag", "rowguid"}),
    #"Split FullName by Delimiter" = Table.SplitColumn(#"Removed CurrentFlag,Rowguid", "Full Name", Splitter.SplitTextByEachDelimiter({" "}, QuoteStyle.Csv, false), {"Full Name.1", "Full Name.2"}),
    #"FullName to FirstName" = Table.TransformColumnTypes(#"Split FullName by Delimiter",{{"Full Name.1", type text}, {"Full Name.2", type text}}),
    #"FullName to LastName" = Table.RenameColumns(#"FullName to FirstName",{{"Full Name.1", "First Name"}, {"Full Name.2", "Last Name"}}),
    #"Removed column LoginID" = Table.RemoveColumns(#"FullName to LastName",{"LoginID"})
in
    #"Removed column LoginID"